INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL10', 'IL10@infolab.com', 'BHEntity1', 12, 288, 300);    
INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL11', 'IL11@infolab.com', 'BHEntity2', 5, 35, 40);    
INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL12', 'IL12@infolab.com', 'BHEntity3', 25, 75, 100);
INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL13', 'IL13@infolab.com', 'BHEntity4', 12, 288, 300);    
INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL14', 'IL14@infolab.com', 'BHEntity5', 5, 35, 40);    
INSERT INTO ELEARNING_POINTS(USERID,EMAIL,BHENTITY ,REDEMMED ,BALANCE ,CUMULATIVE ) VALUES ('IL15', 'IL15@infolab.com', 'BHEntity6', 25, 75, 100);  