DROP TABLE IF EXISTS ELEARNING_POINTS;  
CREATE TABLE ELEARNING_POINTS (  
USERID VARCHAR(50) NOT NULL, 
EMAIL VARCHAR(50) NOT NULL,  
BHENTITY VARCHAR(50) NOT NULL,  
REDEMMED LONG NOT NULL,
BALANCE LONG NOT NULL,
CUMULATIVE LONG NOT NULL
);  